title: Paras Dhiman
logo: "/pfp.png"
description: >
  Welcome to my portfolio website! I'm passionate about technology and eager to make a positive impact. Connect with me on LinkedIn or shoot me an email!
social:
  - title: LinkedIn
    icon: linkedin
    url: https://www.linkedin.com/in/paras-dhiman-3ba729147/
  - title: Gmail
    icon: gmail
    url: mailto:dhimanparas000@gmail.com
theme: jekyll-theme-minimal
